# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VAUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import time
from datetime import date
import res_rc
import sys
import requests
from PyQt5.QtCore import QTimer, QTime
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 454)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.mainui = QtWidgets.QWidget(MainWindow)
        self.mainui.setObjectName("mainui")
        self.background = QtWidgets.QLabel(self.mainui)
        self.background.setGeometry(QtCore.QRect(-40, -10, 751, 451))
        self.background.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setLineWidth(4)
        self.background.setMidLineWidth(2)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/gifs/resources/abstract11.jpg.png"))
        self.background.setScaledContents(True)
        self.background.setOpenExternalLinks(False)
        self.background.setObjectName("background")
        self.label_core = QtWidgets.QLabel(self.mainui)
        self.label_core.setGeometry(QtCore.QRect(380, 140, 231, 171))
        self.label_core.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.label_core.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_core.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_core.setLineWidth(4)
        self.label_core.setMidLineWidth(0)
        self.label_core.setText("")
        self.label_core.setPixmap(QtGui.QPixmap(":/gifs/resources/core1.gif"))
        self.label_core.setScaledContents(True)
        self.label_core.setObjectName("label_core")
        self.label_1 = QtWidgets.QLabel(self.mainui)
        self.label_1.setGeometry(QtCore.QRect(80, 70, 231, 41))
        self.label_1.setText("")
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.mainui)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 231, 41))
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.mainui)
        self.label_3.setGeometry(QtCore.QRect(80, 250, 231, 41))
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.mainui)
        self.label_4.setGeometry(QtCore.QRect(350, 70, 191, 51))
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_misc = QtWidgets.QLabel(self.mainui)
        self.label_misc.setGeometry(QtCore.QRect(570, 50, 41, 41))
        self.label_misc.setText("")
        self.label_misc.setScaledContents(True)
        self.label_misc.setObjectName("label_misc")

        self.label_core = QtWidgets.QLabel(self.mainui)
        self.movie = QtGui.QMovie(":/gifs/resources/core1.gif")
        self.label_core.setMovie(self.movie)
        self.label_core.setGeometry(380, 140, 231, 171)
        self.label_core.setScaledContents(True)
        self.movie.start()

        self.exit_button = QtWidgets.QPushButton(self.mainui)
        self.exit_button.setGeometry(QtCore.QRect(410, 320, 161, 31))
        self.exit_button.setAutoFillBackground(False)
        self.exit_button.setStyleSheet("background-image: url(:/gifs/resources/exit - text.png);")
        self.exit_button.setText("")
        self.exit_button.setCheckable(True)
        self.exit_button.setFlat(True)
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.mainui)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actioninfo = QtWidgets.QAction(MainWindow)
        self.actioninfo.setObjectName("actioninfo")
        self.menuAbout.addAction(self.actioninfo)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.temp=" "

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showTime(self):
        current_time = QTime.currentTime()
        label_time = current_time.toString('hh : mm : ss AP ')
        self.label_1.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">"
                                        + label_time + "</span></p></body></html>")

    def get_temp(self):
        #API ID: 76ababf608808a939dd961a3e8adea29
        resp = requests.get(
            "http://api.openweathermap.org/data/2.5/weather?appid=76ababf608808a939dd961a3e8adea29&q=Faridabad")
        weather = resp.json()
        if (weather['cod']) == '404':
            self.temp = "error"
        else:
            weather_data = weather['main']
            self.temp = str(int(weather_data["temp"] - 273)) +u"\N{DEGREE SIGN} C"
        return(self.temp)

    def close(self):
        sys.exit()

    def mainn(self):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Assistant"))
        self.timer = QTimer()
        self.timer.timeout.connect(self.showTime)
        self.timer.start(1000)
        self.label_1.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">"
                                        + time.strftime("%I : %M : %S %p  ") + "</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">"
                                        + date.today().strftime("%B %d, %Y") + "</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">"
                                        + date.today().strftime("%A ,")+ self.get_temp() + "</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:300; color:#ffffff;\">"
                                        "status: <u>Running...</u></span></p></u></body></html>"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))

        self.exit_button.clicked.connect(self.close)
        self.actioninfo.setText(_translate("MainWindow", "info"))

class VAUIThread(QThread):
    def __init__(self):
        super(VAUIThread, self).__init__()
        self.run()

    def run(self):
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

abc = VAUIThread()
abc.start()
